In [1]:
import re
import numpy as np
from keras.preprocessing.sequence import pad_sequences
from keras.preprocessing.text import one_hot

C:\Users\sreenath.elloti\AppData\Local\Continuum\anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
docs = ['Well done!', 'Good work', 'Great effort', 'nice work', 'Excellent!',
        'Weak', 'Poor effort!', 'not good', 'poor work', 'Could have done better.']


In [3]:
labels = [1, 1, 1, 1, 1, 0, 0, 0, 0, 0]

In [8]:
own_embedding_vocab_size = 10

In [9]:
encoded_docs_oe = [one_hot(d, own_embedding_vocab_size) for d in docs]
print(encoded_docs_oe)

[[8, 4], [6, 4], [6, 2], [9, 4], [3], [6], [4, 2], [5, 6], [4, 4], [2, 5, 4, 5]]


In [10]:
maxlen = 5
padded_docs_oe = pad_sequences(encoded_docs_oe, maxlen=maxlen, padding='post')
print(padded_docs_oe)

[[8 4 0 0 0]
 [6 4 0 0 0]
 [6 2 0 0 0]
 [9 4 0 0 0]
 [3 0 0 0 0]
 [6 0 0 0 0]
 [4 2 0 0 0]
 [5 6 0 0 0]
 [4 4 0 0 0]
 [2 5 4 5 0]]
